---
title: "About the data"
description: |
#author:
#  - name: Nora Jones 
#    url: https://example.com/norajones
#   affiliation: Spacely Sprockets
#   affiliation_url: https://example.com/spacelysprokets
#   date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Variables 

```{r echo= FALSE, eval=TRUE}
Variables <- c("Date", "StateOfOccurrence","Location" ,"Model","Registration", "Operator","StateOfOperator","StateOfRegistry", "FlightPhase","Class","Fatalities","Over2250","Over5700","ScheduledCommercial","InjuryLevel","TypeDesignator","Helicopter","Airplane","Engine","EngineType","Official","OccCats","Risk","Year")

Explanations <-c("Date of occurrence in datetime format (time is default 00:00:00.000Z)",
            "Country of occurrence ",
            "City or nearest city of occurrence",
            "Aircraft type",
            "Aircraft registration code",
            "Name of Operator (airline, institution or responsible for the aircraft operation)",
            "Operator's country",
            "Country of aircraft registration ",
            "Flight Phase of occurrence (take off, landing, approach, etc.)",
            "Accident (unique value). rmk: only 'Accident' class was selected in this dataset (no incidens)",
            "Number of fatal victims",
            "If aircraft basic operational weight (empty) is greater than 2250KG",
            "If aircraft basic operational weight (empty) is greater than 5700KG",
            "If it was a scheduled commercial flight (airlines mostly)",
            "Level of injuries on person/people involved in the occurrence",
            "Aircraft type code (https://cfapps.icao.int/doc8643/reports/Part2-By%20Type%20Designator(Decode).pdf)",
            "if it was a helicopter",
            "If it was an airplane",
            "Number of engines in the aircraft",
            "Aircraft engine type (jet, turboprop or piston)",
            "If ICAO was designated to participate in the accident investigation",
            "All risk types involved in the occurrence, coded according to HRCs ( High Risks Categories codes) - ICAO",
            "Main risk type involved in the occurrence, coded according to HRCs(( High Risks Categories codes) - ICAO",
            "Year of occurrence")

table <- data.frame(Variables = Variables, Explanations = Explanations)

knitr::kable(table)
```




## Data Preparation
Here are the packages I used for this data visualization:

```{r dataprep, echo= TRUE, eval=TRUE}
library(dplyr)
library(tidyverse)
library(knitr)
```

Read the data:

```{r importdata, echo=TRUE, eval=TRUE}
df<-read.csv("data/ICAO_accidents.csv") 

#Country abbreviation to country full name
world <- read.csv("data/world.csv") %>% 
    rename(StateOfOccurrence = Abbreviation)
df <- left_join(df, world)
```

We are only looking at the accidents of **commercial** flights:

```{r echo=TRUE, eval=TRUE}
com <- filter(df, df$ScheduledCommercial == "True") %>% select(Year, Country, Model, Fatalities, Over2250, Over5700, InjuryLevel, Risk, FlightPhase, EngineType)
kable(head(com[1:4,]))
```

Add up the fatality number for each year for each country:

```{r echo=TRUE, eval=TRUE}
coun<- com %>% group_by(Country, na.rm = T) %>% mutate(num_fatal = sum(Fatalities, na.rm = T))
```

Add up the fatality number for each year for each Flight Phase:

```{r echo=TRUE, eval=TRUE}
FP <- com %>% group_by(FlightPhase, na.rm = T) %>% mutate(num_fatal = sum(Fatalities, na.rm = T))
```





